# Script to Convert File from GeoTiff to NetCDF
**Input Data:** GeoTiff file  
**Output Data:** NetCDF file  
**Description:** Extracts data from a GeoTiff (.tif) file and exports them to a new NetCDF(.nc) file.  
**Date:** July 2022  
**Creator:** Emma Perkins 

### Install Important Packages
More information about the NSIDC package for converting from polar stereographic projection to standard lat/lon coordinates can be found at: https://github.com/nsidc/polarstereo-lonlat-convert-py

In [1]:
# install NSIDC package for converting from polar stereographic projection to lat/lon coordinates
!pip install /glade/scratch/eperkins/coordinate_convert/polarstereo_lonlat_convert_py/

Processing /glade/scratch/eperkins/coordinate_convert/polarstereo_lonlat_convert_py
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for polarstereo-lonlat-convert-py: filename=polarstereo_lonlat_convert_py-1.0.0-py3-none-any.whl size=6274 sha256=27e00a8dac7ac4a617428030a641a53dff8244fe294e93cf8d821a1a0086b839
  Stored in directory: /glade/scratch/eperkins/pip-ephem-wheel-cache-lp5051p1/wheels/27/20/52/2db6fab80c2735aaf2030ad714b62073abafefb318d4d00673
Successfully built polarstereo-lonlat-convert-py
  Attempting uninstall: polarstereo-lonlat-convert-py
    Found existing installation: polarstereo-lonlat-convert-py 1.0.0
    Uninstalling polarstereo-lonlat-convert-py-1.0.0:
      Successfully uninstalled polarstereo-lonlat-convert-py-1.0.0


In [2]:
# import relevant packages
import xarray as xr
# from osgeo import gdal
import numpy as np
import datetime
from polar_convert.constants import NORTH
from polar_convert import polar_xy_to_lonlat
from polar_convert.constants import SOUTH

### Load Files

In [3]:
tif_in_path = '/glade/scratch/eperkins/data/'
tif_in_file = 'cmc_sdepth_dly_2000_v01.2.tif'

data = xr.open_rasterio(tif_in_path+tif_in_file)

/glade/work/eperkins/miniconda3/envs/analysis3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: open_rasterio is Deprecated in favor of rioxarray. For information about transitioning, see: https://corteva.github.io/rioxarray/stable/getting_started/getting_started.html
  after removing the cwd from sys.path.


### Convert Spatial Coordinates to Standard Lat/Lon

In [13]:
re = 6378.137  # Earth Radius
e = 0.01671  # Earth eccentricity
hemisphere = SOUTH
true_scale_lat = 70  # true-scale latitude in degrees

In [14]:
x_coords = data.x.to_numpy()
y_coords = data.y.to_numpy()

In [15]:
new_lon, new_lat = polar_xy_to_lonlat(x_coords, y_coords, true_scale_lat, re, e, hemisphere)

In [17]:
print(len(new_lat))

706


In [4]:
data = data.rename({'band': 'time', 'x': 'lon', 'y': 'lat'})
new_data = np.zeros([len(data.time), len(data.lat), len(data.lon)])

In [ ]:
for t in range(0, len(data.time)):
    for x in range(0, len(data.lon)):
        for y in range(0, len(data.lat)):
            new_data[t, y, x] = float(data[t][y][x])
print(t)

In [8]:
new_lat = np.zeros(len(data.y))
new_lon = np.zeros(len(data.x))
for i in range(0, len(data.x)):
    point_x = float(data.x[i])
    point_y = float(data.y[0])
    lon_point, lat_point = polar_xy_to_lonlat(point_x, point_y, true_scale_lat, re, e, hemisphere)
    new_lon[i] = lon_point
for j in range(0, len(data.y)):
    point_x = float(data.x[0])
    point_y = float(data.y[j])
    lon_point, lat_point = polar_xy_to_lonlat(point_x, point_y, true_scale_lat, re, e, hemisphere)
    new_lat[j] = lat_point

In [9]:
new_lat = np.zeros(len(data.y))
new_lon = np.zeros(len(data.x))
for i in range(0, len(data.x)):
    x_point = float(data.x[i])
    y_point = float(data.y[0])
    new_lon[i], new_lat[i] = polar_xy_to_lonlat(x_point, y_point, true_scale_lat, re, e, hemisphere)
    print('step')

step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step
step


In [11]:
new_lat = np.zeros(len(data.y))
new_lon = np.zeros(len(data.x))
new_lon, new_lat = polar_xy_to_lonlat(data.x, data.y, true_scale_lat, re, e, hemisphere)

In [29]:
time_coord = np.zeros(len(data.band))

In [ ]:
for t in range(0, len(data.band)):
    for x in range(0, len(data.x)):
        for y in range(0, len(data.y)):
            
        

In [27]:
print(data)

<xarray.DataArray (band: 366, y: 706, x: 706)>
array([[[0., 0., ..., 0., 0.],
        [0., 0., ..., 0., 0.],
        ...,
        [0., 0., ..., 0., 0.],
        [0., 0., ..., 0., 0.]],

       [[0., 0., ..., 0., 0.],
        [0., 0., ..., 0., 0.],
        ...,
        [0., 0., ..., 0., 0.],
        [0., 0., ..., 0., 0.]],

       ...,

       [[0., 0., ..., 0., 0.],
        [0., 0., ..., 0., 0.],
        ...,
        [0., 0., ..., 0., 0.],
        [0., 0., ..., 0., 0.]],

       [[0., 0., ..., 0., 0.],
        [0., 0., ..., 0., 0.],
        ...,
        [0., 0., ..., 0., 0.],
        [0., 0., ..., 0., 0.]]])
Coordinates:
  * band     (band) int64 1 2 3 4 5 6 7 8 9 ... 359 360 361 362 363 364 365 366
  * y        (y) float64 8.394e+06 8.37e+06 8.346e+06 ... -8.37e+06 -8.394e+06
  * x        (x) float64 -8.394e+06 -8.37e+06 -8.346e+06 ... 8.37e+06 8.394e+06
Attributes:
    transform:      (23812.498583569406, 0.0, -8405812.0, 0.0, -23812.4985835...
    crs:            +proj=stere +lat_0=

In [26]:
print(data[0])

<xarray.DataArray (y: 706, x: 706)>
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])
Coordinates:
    band     int64 1
  * y        (y) float64 8.394e+06 8.37e+06 8.346e+06 ... -8.37e+06 -8.394e+06
  * x        (x) float64 -8.394e+06 -8.37e+06 -8.346e+06 ... 8.37e+06 8.394e+06
Attributes:
    transform:      (23812.498583569406, 0.0, -8405812.0, 0.0, -23812.4985835...
    crs:            +proj=stere +lat_0=90 +lat_ts=60 +lon_0=10 +x_0=0 +y_0=0 ...
    res:            (23812.498583569406, 23812.498583569406)
    is_tiled:       0
    nodatavals:     (-1.7e+308, -1.7e+308, -1.7e+308, -1.7e+308, -1.7e+308, -...
    scales:         (1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
    offsets:        (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0...
    AREA_OR_POINT:  Area


In [28]:
print(data[0][0])

<xarray.DataArray (x: 706)>
array([0., 0., 0., ..., 0., 0., 0.])
Coordinates:
    band     int64 1
    y        float64 8.394e+06
  * x        (x) float64 -8.394e+06 -8.37e+06 -8.346e+06 ... 8.37e+06 8.394e+06
Attributes:
    transform:      (23812.498583569406, 0.0, -8405812.0, 0.0, -23812.4985835...
    crs:            +proj=stere +lat_0=90 +lat_ts=60 +lon_0=10 +x_0=0 +y_0=0 ...
    res:            (23812.498583569406, 23812.498583569406)
    is_tiled:       0
    nodatavals:     (-1.7e+308, -1.7e+308, -1.7e+308, -1.7e+308, -1.7e+308, -...
    scales:         (1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1...
    offsets:        (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0...
    AREA_OR_POINT:  Area


In [25]:
print(float(data[0][0][0]))

0.0


In [20]:
print(new_lon[350])

<xarray.DataArray 'x' (y: 706)>
array([180.40634623, 180.40750223, 180.40866482, 180.40983407,
       180.41101002, 180.41219274, 180.41338229, 180.41457872,
       180.4157821 , 180.41699249, 180.41820994, 180.41943452,
       180.4206663 , 180.42190533, 180.42315168, 180.42440542,
       180.42566661, 180.42693531, 180.4282116 , 180.42949555,
       180.43078722, 180.43208668, 180.433394  , 180.43470926,
       180.43603252, 180.43736387, 180.43870337, 180.4400511 ,
       180.44140713, 180.44277155, 180.44414443, 180.44552585,
       180.44691589, 180.44831463, 180.44972216, 180.45113855,
       180.45256389, 180.45399826, 180.45544175, 180.45689446,
       180.45835646, 180.45982784, 180.46130871, 180.46279914,
       180.46429923, 180.46580908, 180.46732878, 180.46885843,
       180.47039813, 180.47194797, 180.47350806, 180.47507849,
       180.47665938, 180.47825083, 180.47985293, 180.48146581,
       180.48308956, 180.4847243 , 180.48637015, 180.48802721,
       180.48969559, 18

In [24]:
polar_xy_to_lonlat(-11906.249291785061, 0, true_scale_lat, re, e, hemisphere)

[270.0, 2.188951478754743]

In [20]:
polar_xy_to_lonlat(-6417468.368271954, 0, true_scale_lat, re, e, hemisphere)

[270.0, -89.77918253489976]

In [22]:
polar_xy_to_lonlat(-7417593.30878187, 0, true_scale_lat, re, e, hemisphere)

[270.0, -89.8089556168932]

In [5]:
# rename band to time
data = data.rename({'band': 'time', 'x': 'lon', 'y': 'lat'})

In [6]:
data['lat'] = new_lat
data['lon'] = new_lon

ValueError: cannot add coordinates with new dimensions to a DataArray

In [7]:
print(new_lat)
print(new_lon)

[-89.88062361 -89.88045416 -89.88028447 -89.88011455 -89.87994438
 -89.87977399 -89.87960335 -89.87943249 -89.87926139 -89.87909006
 -89.8789185  -89.87874671 -89.87857469 -89.87840244 -89.87822997
 -89.87805728 -89.87788437 -89.87771123 -89.87753787 -89.8773643
 -89.8771905  -89.87701649 -89.87684227 -89.87666784 -89.87649319
 -89.87631833 -89.87614327 -89.87596799 -89.87579252 -89.87561684
 -89.87544095 -89.87526487 -89.87508859 -89.87491211 -89.87473544
 -89.87455857 -89.87438152 -89.87420427 -89.87402683 -89.87384921
 -89.8736714  -89.87349342 -89.87331525 -89.8731369  -89.87295838
 -89.87277968 -89.87260081 -89.87242177 -89.87224256 -89.87206319
 -89.87188365 -89.87170395 -89.87152409 -89.87134407 -89.8711639
 -89.87098358 -89.8708031  -89.87062248 -89.87044171 -89.8702608
 -89.87007975 -89.86989856 -89.86971723 -89.86953577 -89.86935418
 -89.86917246 -89.86899062 -89.86880865 -89.86862656 -89.86844436
 -89.86826204 -89.86807961 -89.86789707 -89.86771442 -89.86753167
 -89.86734883

### Convert bands to time coordinate (each band is one day)

In [4]:
# convert bands to julian date
julian_date = np.zeros(len(data.time))
year = 99000  # replace first two digits with last two digits of specific year ex: 1999 --> 99000, 2001 --> 01000
for i in range(0, len(data.time)):
    day = int(data.time[i])
    new_day = year + day
    julian_date[i] = int(new_day)

In [5]:
# convert julian date to datetime index
time_coord = np.empty(len(data.time), dtype=object)
for i in range(0, len(data.time)):
    day_string = str(int(julian_date[i]))
    time_coord[i] = datetime.datetime.strptime(day_string, '%y%j')

In [6]:
# replace time coordinate with new datetime array
data['time'] = time_coord

### Convert to NetCDF File and Export

In [5]:
nc_in_path = tif_out_path
nc_in_file = tif_out_file
nc_out_path = '/glade/scratch/eperkins/data/tif_to_nc/'
nc_out_file = 'corr_cmc_sdepth_dly_1998_v01.2.nc'
gdal.Translate(nc_out_path+nc_out_file, nc_in_path+nc_in_file, format='NetCDF')

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x2ad39ea17840> >